---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3158121894-5nUg9vIGNbThbM4XCyBx8KlVx6HdENKFnsmeLms
:access_token_secret: mhcrBzQBpYeepMQTTJ8QY28I2909pUzkO7OHv9CuQcYDK
